apiVersion: v1
kind: Service
metadata:
  name: legacywebshop
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32380
  selector:
    app: legacywebshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacywebshop
spec:
  selector:
    matchLabels:
      app: legacywebshop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: legacywebshop
    spec:
      containers:
      - image: legacywebshop:latest
        name: legacywebshop
        imagePullPolicy: Never
        command: ["tail", "-f", "/dev/null"]
        env:
          # Use secret in real usage
        - name: DB_HOST
          value: mysql
        ports:
        - containerPort: 8080
          name: legacywebshop
